description: TMUX profile
sessions:
  - name: dev
    dir: ~/Development/tmux-profile
    attach: true
    windows:
      - name: cook
        cmd: dev && cd cookbooks/app-analysis && clear
        panes:
          - cmd: dev && cd cookbooks/app-pmt && clear
            split: h
          - cmd: dev && cd cookbooks/databags && clear
            split: v
          - cmd: dev && cd quid/analysis && clear
            split: v
      - name: pmt
        cmd: pmt && clear
      - name: vim
        cmd: pmt && clear
