description: TMUX profile
sessions:

    # customize per env
  - name: apple
    attach: true
    windows:
      - name: '0'
        cmd: dev && clear
      - name: '1'
        cmd: dev && clear
      - name: '2'
        cmd: dev && clear

  - name: banana
    attach: true
    windows:
      - name: '0'
        cmd: dev && clear
      - name: '1'
        cmd: dev && clear
      - name: '2'
        cmd: dev && clear

  - name: carrot
    attach: true
    windows:
      - name: '0'
        cmd: dev && clear
      - name: '1'
        cmd: dev && clear
      - name: '2'
        cmd: dev && clear
