description: TMUX profile
sessions:

  - name: cookbooks
    dir: ~/Development/tmux-profile
    attach: true
    windows:
      - name: cookbook
        cmd: dev && cd cookbooks/service_quidweb && clear
      - name: source
        panes:
          - cmd: dev && cd quid/analysis && clear
            split: v
        cmd: quidweb && clear
      - name: databag
        cmd: dev && cd cookbooks/databags && clear

  - name: quidweb
    dir: ~/Development/tmux-profile
    attach: true
    windows:
      - name: dev
        cmd: quidweb && clear
      - name: source 
        cmd: quidweb && clear
      - name: vim
        cmd: quidweb && clear

  - name: screener
    dir: ~/Development/tmux-profile
    attach: true
    windows:
      - name: dev
        cmd: dev && cd tools/screener && clear
      - name: source
        cmd: dev && cd tools/screener && clear
      - name: vim
        cmd: dev && cd tools/screener && clear
