description: TMUX profile
sessions:

  - name: cookbooks
    dir: ~/Development/tmux-profile
    attach: true
    windows:
      - name: cookbook
        cmd: dev && cd cookbooks/service_quidweb && clear
      - name: databag
        cmd: dev && cd cookbooks/databags && clear

  - name: quidweb
    dir: ~/Development/tmux-profile
    attach: true
    windows:
      - name: dev
        cmd: qw && clear
      - name: source
        cmd: qw && clear
      - name: vim 
        cmd: qw && clear

  - name: schema
    dir: ~/Development/tmux-profile
    attach: true
    windows:
      - name: dev
        cmd: qw && cd schema && clear
  
  - name: screener 
    dir: ~/Development/tmux-profile
    attach: true
    windows:
      - name: dev
        cmd: sc && clear
      - name: source
        cmd: sc && clear
      - name: vim 
        cmd: sc && clear
