description: TMUX profile
sessions:
  - name: dev
    dir: ~/tmux-profile
    attach: true
    windows:
      - name: vim
        cmd: cd ~/Dropbox && clear
        panes:
          - cmd: cd ~/Dropbox && clear
            split: v
            size: 20
          - cmd: cd ~/Dropbox && clear
            split: h
      - name: blue
        cmd: cd ~/Dropbox/dev && clear
        panes:
          - cmd: cd ~/Dropbox/dev && clear
            split: v
            size: 20
      - name: green
        cmd: cd ~/Dropbox/dev && clear
        panes:
          - cmd: cd ~/Dropbox/dev && clear
            split: v
            size: 20
