description: TMUX profile
sessions:

  - name: cookbooks
    dir: ~/Development/tmux-profile
    attach: true
    windows:
      - name: analysis
        cmd: dev && cd cookbooks/app-analysis && clear
        panes:
          - cmd: dev && cd quid/analysis && clear
            split: v
      - name: quidweb
        cmd: quidweb && clear
      - name: databags
        cmd: dev && cd cookbooks/databags && clear

  - name: quidweb
    dir: ~/Development/tmux-profile
    attach: true
    windows:
      - name: dev
        cmd: quidweb && clear
      - name: dev
        cmd: quidweb && clear
      - name: vim 
        cmd: quidweb && clear
